// This file was auto-generated by Fern from our API Definition.

package client

import (
	context "context"
	http "net/http"
	audioseparation "sdk/audioseparation"
	core "sdk/core"
	deprecatedstreaming "sdk/deprecatedstreaming"
	dictionaries "sdk/dictionaries"
	dub "sdk/dub"
	folders "sdk/folders"
	languages "sdk/languages"
	option "sdk/option"
	projectsetup "sdk/projectsetup"
	story "sdk/story"
	streaming "sdk/streaming"
	texttoaudio "sdk/texttoaudio"
	texttospeech "sdk/texttospeech"
	texttovoice "sdk/texttovoice"
	transcription "sdk/transcription"
	translatedstory "sdk/translatedstory"
	translatedtts "sdk/translatedtts"
	translation "sdk/translation"
	voicecloning "sdk/voicecloning"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	AudioSeparation     *audioseparation.Client
	Dub                 *dub.Client
	Folders             *folders.Client
	Languages           *languages.Client
	Story               *story.Client
	TranslatedStory     *translatedstory.Client
	TextToAudio         *texttoaudio.Client
	TextToVoice         *texttovoice.Client
	TextToSpeech        *texttospeech.Client
	Translation         *translation.Client
	Transcription       *transcription.Client
	TranslatedTts       *translatedtts.Client
	Streaming           *streaming.Client
	VoiceCloning        *voicecloning.Client
	Dictionaries        *dictionaries.Client
	ProjectSetup        *projectsetup.Client
	DeprecatedStreaming *deprecatedstreaming.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:              options.ToHeader(),
		AudioSeparation:     audioseparation.NewClient(opts...),
		Dub:                 dub.NewClient(opts...),
		Folders:             folders.NewClient(opts...),
		Languages:           languages.NewClient(opts...),
		Story:               story.NewClient(opts...),
		TranslatedStory:     translatedstory.NewClient(opts...),
		TextToAudio:         texttoaudio.NewClient(opts...),
		TextToVoice:         texttovoice.NewClient(opts...),
		TextToSpeech:        texttospeech.NewClient(opts...),
		Translation:         translation.NewClient(opts...),
		Transcription:       transcription.NewClient(opts...),
		TranslatedTts:       translatedtts.NewClient(opts...),
		Streaming:           streaming.NewClient(opts...),
		VoiceCloning:        voicecloning.NewClient(opts...),
		Dictionaries:        dictionaries.NewClient(opts...),
		ProjectSetup:        projectsetup.NewClient(opts...),
		DeprecatedStreaming: deprecatedstreaming.NewClient(opts...),
	}
}

func (c *Client) GetSwaggerDocsDocsGet(
	ctx context.Context,
	opts ...option.RequestOption,
) (interface{}, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://client.camb.ai/apis"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/" + "docs"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response interface{}
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodGet,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

func (c *Client) GetRedocDocsRedocsGet(
	ctx context.Context,
	opts ...option.RequestOption,
) (interface{}, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://client.camb.ai/apis"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/" + "redocs"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response interface{}
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodGet,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

func (c *Client) GetOpenapiSchemaOpenapiJSONGet(
	ctx context.Context,
	opts ...option.RequestOption,
) (interface{}, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://client.camb.ai/apis"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/" + "openapi.json"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response interface{}
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodGet,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
