// This file was auto-generated by Fern from our API Definition.

package projectsetup

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	cambaigosdk "github.com/camb-ai/cambai-go-sdk"
	core "github.com/camb-ai/cambai-go-sdk/core"
	option "github.com/camb-ai/cambai-go-sdk/option"
	io "io"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Creates a new project setup with transcription capabilities.
//
// This endpoint allows users to create a new project by providing media content
// (either as a file upload or URL), specifying source and target languages, and
// other project metadata. The function validates inputs, checks file size limitations,
// and initiates the project setup process.
//
// Args:
//
//	request_payload (CreateProjectSetupRequestPayload): Complete project configuration
//	        including media URL, source/target languages, project metadata, and
//	        processing preferences such as audio track selection and dictionary choices.
//	    api_key_obj_and_subscription: Dependency injection providing validated API key
//	        object and associated subscription details for authorization and usage
//	        limit enforcement.
//	    traceparent (str | None, optional): OpenTelemetry trace parent header for
//	        distributed tracing across microservices. Enables request correlation
//	        and performance monitoring throughout the processing pipeline.
//
// Returns:
//
//	Project setup response with project details and processing status.
//
// Raises:
//
//	HTTPException:
//	    - 400: If neither media_file nor media_url is provided
//	    - 400: If uploaded file has no filename
//	    - 413: If uploaded file exceeds size limit
func (c *Client) CreateProject(
	ctx context.Context,
	request *cambaigosdk.CreateProjectSetupRequestPayload,
	opts ...option.RequestOption,
) (*cambaigosdk.CreateProjectSetupOut, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://client.camb.ai/apis"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/" + "project-setup"

	queryParams, err := core.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 422:
			value := new(cambaigosdk.UnprocessableEntityError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	var response *cambaigosdk.CreateProjectSetupOut
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:          endpointURL,
			Method:       http.MethodPost,
			MaxAttempts:  options.MaxAttempts,
			Headers:      headers,
			Client:       options.HTTPClient,
			Request:      request,
			Response:     &response,
			ErrorDecoder: errorDecoder,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

func (c *Client) CreateProjectSetupTaskStatus(
	ctx context.Context,
	taskID string,
	request *cambaigosdk.CreateProjectSetupTaskStatusProjectSetupTaskIDGetRequest,
	opts ...option.RequestOption,
) ([]*cambaigosdk.GetCreateProjectSetupResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://client.camb.ai/apis"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"project-setup/%v", taskID)

	queryParams, err := core.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 422:
			value := new(cambaigosdk.UnprocessableEntityError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	var response []*cambaigosdk.GetCreateProjectSetupResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:          endpointURL,
			Method:       http.MethodGet,
			MaxAttempts:  options.MaxAttempts,
			Headers:      headers,
			Client:       options.HTTPClient,
			Response:     &response,
			ErrorDecoder: errorDecoder,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Retrieves the final result of a completed project setup.
//
// This endpoint provides access to the final results of a completed project setup.
// It verifies that the authenticated user has access to the requested run_id and
// validates that the run is of the correct type (`DUB_PROJECT`) before returning results.
//
// Note:
//
//	This endpoint should only be called by users to retrieve their run results via API.
//	Access validation is performed to ensure users can only access their own runs.
//
// Args:
//
//	run_id: Positive integer ID of the project setup run.
//	api_key_obj: API key authentication data from dependency.
//	traceparent: OpenTelemetry trace header for distributed tracing.
//
// Returns:
//
//	GetCreateProjectSetupResponse: Project setup results including run details.
//
// Raises:
//
//	HTTPException:
//	    - 404: If the run_id is not found
//	    - 400: If the run type is not valid for this endpoint (must be DUB_PROJECT)
func (c *Client) GetProjectSetupResult(
	ctx context.Context,
	runID *int,
	request *cambaigosdk.GetProjectSetupResultProjectSetupResultRunIDGetRequest,
	opts ...option.RequestOption,
) (*cambaigosdk.GetCreateProjectSetupResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://client.camb.ai/apis"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"project-setup-result/%v", runID)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 422:
			value := new(cambaigosdk.UnprocessableEntityError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	var response *cambaigosdk.GetCreateProjectSetupResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:                endpointURL,
			Method:             http.MethodGet,
			MaxAttempts:        options.MaxAttempts,
			Headers:            headers,
			Client:             options.HTTPClient,
			Response:           &response,
			ResponseIsOptional: true,
			ErrorDecoder:       errorDecoder,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

func (c *Client) GetProjectSetupRunsResults(
	ctx context.Context,
	request *cambaigosdk.GetProjectSetupRunsResultsProjectSetupResultsPostRequest,
	opts ...option.RequestOption,
) ([]*cambaigosdk.GetCreateProjectSetupResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://client.camb.ai/apis"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/" + "project-setup-results"

	queryParams, err := core.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 422:
			value := new(cambaigosdk.UnprocessableEntityError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	var response []*cambaigosdk.GetCreateProjectSetupResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:          endpointURL,
			Method:       http.MethodPost,
			MaxAttempts:  options.MaxAttempts,
			Headers:      headers,
			Client:       options.HTTPClient,
			Request:      request,
			Response:     &response,
			ErrorDecoder: errorDecoder,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
