// This file was auto-generated by Fern from our API Definition.

package cambai

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type BodyCreateAudioSeparationAudioSeparationPost struct {
	Traceparent        *string `json:"-" url:"-"`
	RunID              *int    `json:"-" url:"run_id,omitempty"`
	ProjectName        *string `json:"project_name,omitempty" url:"project_name,omitempty"`
	ProjectDescription *string `json:"project_description,omitempty" url:"project_description,omitempty"`
	FolderID           *int    `json:"folder_id,omitempty" url:"folder_id,omitempty"`
}

type GetAudioSeparationRunInfoAudioSeparationResultRunIDGetRequest struct {
}

type GetAudioSeparationRunsResultsAudioSeparationResultsPostRequest struct {
	Traceparent *string               `json:"-" url:"-"`
	RunID       *int                  `json:"-" url:"run_id,omitempty"`
	Body        *RunIDsRequestPayload `json:"-" url:"-"`
}

func (g *GetAudioSeparationRunsResultsAudioSeparationResultsPostRequest) UnmarshalJSON(data []byte) error {
	body := new(RunIDsRequestPayload)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetAudioSeparationRunsResultsAudioSeparationResultsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type GetAudioSeparationStatusAudioSeparationTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type GetAudioSeparationResultOut struct {
	ForegroundAudioURL string `json:"foreground_audio_url" url:"foreground_audio_url"`
	BackgroundAudioURL string `json:"background_audio_url" url:"background_audio_url"`

	_rawJSON json.RawMessage
}

func (g *GetAudioSeparationResultOut) UnmarshalJSON(data []byte) error {
	type unmarshaler GetAudioSeparationResultOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetAudioSeparationResultOut(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetAudioSeparationResultOut) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
