// This file was auto-generated by Fern from our API Definition.

package cambai

import (
	json "encoding/json"
)

type GetProbeStreamV1StreamProbePostRequest struct {
	Traceparent *string           `json:"-" url:"-"`
	RunID       *int              `json:"-" url:"run_id,omitempty"`
	Body        *GetProbeStreamIn `json:"-" url:"-"`
}

func (g *GetProbeStreamV1StreamProbePostRequest) UnmarshalJSON(data []byte) error {
	body := new(GetProbeStreamIn)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetProbeStreamV1StreamProbePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type GetStreamResultV1StreamStreamIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type StopStreamV1StreamStreamIDStopGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}
