// This file was auto-generated by Fern from our API Definition.

package cambai

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type CreateProjectSetupRequestPayload struct {
	RunID                   *int        `json:"-" url:"run_id,omitempty"`
	ProjectName             *string     `json:"project_name,omitempty" url:"project_name,omitempty"`
	ProjectDescription      *string     `json:"project_description,omitempty" url:"project_description,omitempty"`
	FolderID                *int        `json:"folder_id,omitempty" url:"folder_id,omitempty"`
	MediaURL                string      `json:"media_url" url:"media_url"`
	SourceLanguage          Languages   `json:"source_language" url:"source_language"`
	TargetLanguages         []Languages `json:"target_languages,omitempty" url:"target_languages,omitempty"`
	SelectedAudioTracks     []int       `json:"selected_audio_tracks,omitempty" url:"selected_audio_tracks,omitempty"`
	AddOutputAsAnAudioTrack *bool       `json:"add_output_as_an_audio_track,omitempty" url:"add_output_as_an_audio_track,omitempty"`
	ChosenDictionaries      []int       `json:"chosen_dictionaries,omitempty" url:"chosen_dictionaries,omitempty"`
}

type CreateProjectSetupTaskStatusProjectSetupTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type GetProjectSetupResultProjectSetupResultRunIDGetRequest struct {
}

type GetProjectSetupRunsResultsProjectSetupResultsPostRequest struct {
	RunID *int                  `json:"-" url:"run_id,omitempty"`
	Body  *RunIDsRequestPayload `json:"-" url:"-"`
}

func (g *GetProjectSetupRunsResultsProjectSetupResultsPostRequest) UnmarshalJSON(data []byte) error {
	body := new(RunIDsRequestPayload)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetProjectSetupRunsResultsProjectSetupResultsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type CreateProjectSetupOut struct {
	TaskID string `json:"task_id" url:"task_id"`

	_rawJSON json.RawMessage
}

func (c *CreateProjectSetupOut) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateProjectSetupOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateProjectSetupOut(value)
	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateProjectSetupOut) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type GetCreateProjectSetupResponse struct {
	RunID          int             `json:"run_id" url:"run_id"`
	ProjectDetails *ProjectDetails `json:"project_details,omitempty" url:"project_details,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetCreateProjectSetupResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetCreateProjectSetupResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetCreateProjectSetupResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetCreateProjectSetupResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type ProjectDetails struct {
	ProjectName        string      `json:"project_name" url:"project_name"`
	ProjectDescription *string     `json:"project_description,omitempty" url:"project_description,omitempty"`
	CreatedAt          time.Time   `json:"created_at" url:"created_at"`
	SourceLanguage     Languages   `json:"source_language" url:"source_language"`
	TargetLanguages    []Languages `json:"target_languages,omitempty" url:"target_languages,omitempty"`
	Duration           *float64    `json:"duration,omitempty" url:"duration,omitempty"`
	FolderID           *int        `json:"folder_id,omitempty" url:"folder_id,omitempty"`
	StudioURL          string      `json:"studio_url" url:"studio_url"`

	_rawJSON json.RawMessage
}

func (p *ProjectDetails) UnmarshalJSON(data []byte) error {
	type embed ProjectDetails
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = ProjectDetails(unmarshaler.embed)
	p.CreatedAt = unmarshaler.CreatedAt.Time()
	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProjectDetails) MarshalJSON() ([]byte, error) {
	type embed ProjectDetails
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at"`
	}{
		embed:     embed(*p),
		CreatedAt: core.NewDateTime(p.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (p *ProjectDetails) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
