// This file was auto-generated by Fern from our API Definition.

package cambai

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/camb-ai/cambai-go-sdk/core"
)

type CreateTextToVoiceRequestPayload struct {
	Traceparent        *string `json:"-" url:"-"`
	ProjectName        *string `json:"project_name,omitempty" url:"project_name,omitempty"`
	ProjectDescription *string `json:"project_description,omitempty" url:"project_description,omitempty"`
	FolderID           *int    `json:"folder_id,omitempty" url:"folder_id,omitempty"`
	// The text to be converted to voice
	Text string `json:"text" url:"text"`
	// Description to use for the created voice
	VoiceDescription string `json:"voice_description" url:"voice_description"`
}

type GetTextToVoiceResultTextToVoiceResultRunIDGetRequest struct {
}

type GetTextToVoiceStatusTextToVoiceTaskIDGetRequest struct {
	Traceparent *string `json:"-" url:"-"`
	RunID       *int    `json:"-" url:"run_id,omitempty"`
}

type GetTextToVoiceResultOut struct {
	Previews []string `json:"previews,omitempty" url:"previews,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetTextToVoiceResultOut) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTextToVoiceResultOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetTextToVoiceResultOut(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetTextToVoiceResultOut) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
