// This file was auto-generated by Fern from our API Definition.

package cambai

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CreateTranslationForExistingStoryRequestPayload struct {
	TargetLanguage Languages `json:"target_language" url:"target_language"`
}

type GetTranslatedStoryRunInfoTranslatedStoryResultRunIDTargetLanguageGetRequest struct {
	// Whether to include the transcription in the response for fetching the result of a Stories Translation run.
	IncludeTranscript *bool `json:"-" url:"include_transcript,omitempty"`
}

type GetTranslatedStoryStatusTranslatedStoryTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type AddTargetLanguageOut struct {
	Message string  `json:"message" url:"message"`
	TaskID  *string `json:"task_id,omitempty" url:"task_id,omitempty"`

	_rawJSON json.RawMessage
}

func (a *AddTargetLanguageOut) UnmarshalJSON(data []byte) error {
	type unmarshaler AddTargetLanguageOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddTargetLanguageOut(value)
	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddTargetLanguageOut) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}
