// This file was auto-generated by Fern from our API Definition.

package cambai

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/camb-ai/cambai-go-sdk/core"
)

type BodyCreateTranscriptionTranscribePost struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
	// Signed URL to audio file for transcription
	Language Languages `json:"language" url:"language"`
	// Signed URL to media file for transcription
	MediaURL *string `json:"media_url,omitempty" url:"media_url,omitempty"`
	// [DEPRECATED] Use 'audio_url' instead
	AudioURL           *string `json:"audio_url,omitempty" url:"audio_url,omitempty"`
	ProjectName        *string `json:"project_name,omitempty" url:"project_name,omitempty"`
	ProjectDescription *string `json:"project_description,omitempty" url:"project_description,omitempty"`
	FolderID           *int    `json:"folder_id,omitempty" url:"folder_id,omitempty"`
}

type GetTranscriptionResultTranscriptionResultRunIDGetRequest struct {
	WordLevelTimestamps *bool `json:"-" url:"word_level_timestamps,omitempty"`
}

type GetTranscriptionResultsTranscriptionResultsPostRequest struct {
	Traceparent *string               `json:"-" url:"-"`
	RunID       *int                  `json:"-" url:"run_id,omitempty"`
	Body        *RunIDsRequestPayload `json:"-" url:"-"`
}

func (g *GetTranscriptionResultsTranscriptionResultsPostRequest) UnmarshalJSON(data []byte) error {
	body := new(RunIDsRequestPayload)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetTranscriptionResultsTranscriptionResultsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type GetTranscriptionTaskStatusTranscribeTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type TranscriptionResult struct {
	Transcript []*Transcript `json:"transcript,omitempty" url:"transcript,omitempty"`

	_rawJSON json.RawMessage
}

func (t *TranscriptionResult) UnmarshalJSON(data []byte) error {
	type unmarshaler TranscriptionResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TranscriptionResult(value)
	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TranscriptionResult) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
