// This file was auto-generated by Fern from our API Definition.

package cambai

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CreateTranslationRequestPayload struct {
	RunID              *int         `json:"-" url:"run_id,omitempty"`
	ProjectName        *string      `json:"project_name,omitempty" url:"project_name,omitempty"`
	ProjectDescription *string      `json:"project_description,omitempty" url:"project_description,omitempty"`
	FolderID           *int         `json:"folder_id,omitempty" url:"folder_id,omitempty"`
	Texts              []string     `json:"texts,omitempty" url:"texts,omitempty"`
	Age                *int         `json:"age,omitempty" url:"age,omitempty"`
	Formality          *Formalities `json:"formality,omitempty" url:"formality,omitempty"`
	Gender             *Gender      `json:"gender,omitempty" url:"gender,omitempty"`
	SourceLanguage     Languages    `json:"source_language" url:"source_language"`
	TargetLanguage     Languages    `json:"target_language" url:"target_language"`
	ChosenDictionaries []int        `json:"chosen_dictionaries,omitempty" url:"chosen_dictionaries,omitempty"`
}

type GetTranslationResultTranslationResultRunIDGetRequest struct {
	Traceparent *string `json:"-" url:"-"`
}

type GetTranslationResultsTranslationResultsPostRequest struct {
	Traceparent *string               `json:"-" url:"-"`
	RunID       *int                  `json:"-" url:"run_id,omitempty"`
	Body        *RunIDsRequestPayload `json:"-" url:"-"`
}

func (g *GetTranslationResultsTranslationResultsPostRequest) UnmarshalJSON(data []byte) error {
	body := new(RunIDsRequestPayload)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetTranslationResultsTranslationResultsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type GetTranslationTaskStatusTranslateTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type CreateTranslationStreamRequestPayload struct {
	Traceparent        *string      `json:"-" url:"-"`
	SourceLanguage     Languages    `json:"source_language" url:"source_language"`
	TargetLanguage     Languages    `json:"target_language" url:"target_language"`
	Text               string       `json:"text" url:"text"`
	Formality          *Formalities `json:"formality,omitempty" url:"formality,omitempty"`
	Gender             *Gender      `json:"gender,omitempty" url:"gender,omitempty"`
	TeamID             *int         `json:"team_id,omitempty" url:"team_id,omitempty"`
	ProjectName        *string      `json:"project_name,omitempty" url:"project_name,omitempty"`
	ProjectDescription *string      `json:"project_description,omitempty" url:"project_description,omitempty"`
	FolderID           *int         `json:"folder_id,omitempty" url:"folder_id,omitempty"`
}

type TranslationResult struct {
	Texts []string `json:"texts,omitempty" url:"texts,omitempty"`

	_rawJSON json.RawMessage
}

func (t *TranslationResult) UnmarshalJSON(data []byte) error {
	type unmarshaler TranslationResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TranslationResult(value)
	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TranslationResult) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
