// This file was auto-generated by Fern from our API Definition.

package cambai

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/camb-ai/cambai-go-sdk/core"
)

type BodyCreateCustomVoiceCreateCustomVoicePost struct {
	RunID       *int    `json:"-" url:"run_id,omitempty"`
	VoiceName   string  `json:"voice_name" url:"voice_name"`
	Gender      Gender  `json:"gender" url:"gender"`
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// By setting true, you consent to making this voice available for other users in the marketplace.
	PublishVoiceToMarketPlace *bool `json:"publish_voice_to_market_place,omitempty" url:"publish_voice_to_market_place,omitempty"`
	Age                       *int  `json:"age,omitempty" url:"age,omitempty"`
	// Language of the voice
	Language *Languages `json:"language,omitempty" url:"language,omitempty"`
	// Enables advanced audio processing to enhance the clarity and quality of the cloned voice output. When set to `true`, additional processing is applied to improve the overall sound experience.
	EnhanceAudio *bool `json:"enhance_audio,omitempty" url:"enhance_audio,omitempty"`
}

type ListVoicesListVoicesGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type CreateCustomVoiceOut struct {
	VoiceID int `json:"voice_id" url:"voice_id"`

	_rawJSON json.RawMessage
}

func (c *CreateCustomVoiceOut) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCustomVoiceOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateCustomVoiceOut(value)
	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateCustomVoiceOut) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type Voice struct {
	ID          int        `json:"id" url:"id"`
	VoiceName   string     `json:"voice_name" url:"voice_name"`
	Gender      *int       `json:"gender,omitempty" url:"gender,omitempty"`
	Age         *int       `json:"age,omitempty" url:"age,omitempty"`
	Language    *Languages `json:"language,omitempty" url:"language,omitempty"`
	Transcript  *string    `json:"transcript,omitempty" url:"transcript,omitempty"`
	Description *string    `json:"description,omitempty" url:"description,omitempty"`
	IsPublished *bool      `json:"is_published,omitempty" url:"is_published,omitempty"`
	SignedURL   *string    `json:"signed_url,omitempty" url:"signed_url,omitempty"`

	_rawJSON json.RawMessage
}

func (v *Voice) UnmarshalJSON(data []byte) error {
	type unmarshaler Voice
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = Voice(value)
	v._rawJSON = json.RawMessage(data)
	return nil
}

func (v *Voice) String() string {
	if len(v._rawJSON) > 0 {
		if value, err := core.StringifyJSON(v._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type ListVoicesListVoicesGetResponseItem struct {
	typeName         string
	StringUnknownMap map[string]interface{}
	Voice            *Voice
}

func NewListVoicesListVoicesGetResponseItemFromStringUnknownMap(value map[string]interface{}) *ListVoicesListVoicesGetResponseItem {
	return &ListVoicesListVoicesGetResponseItem{typeName: "stringUnknownMap", StringUnknownMap: value}
}

func NewListVoicesListVoicesGetResponseItemFromVoice(value *Voice) *ListVoicesListVoicesGetResponseItem {
	return &ListVoicesListVoicesGetResponseItem{typeName: "voice", Voice: value}
}

func (l *ListVoicesListVoicesGetResponseItem) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMap map[string]interface{}
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		l.typeName = "stringUnknownMap"
		l.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	valueVoice := new(Voice)
	if err := json.Unmarshal(data, &valueVoice); err == nil {
		l.typeName = "voice"
		l.Voice = valueVoice
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l ListVoicesListVoicesGetResponseItem) MarshalJSON() ([]byte, error) {
	switch l.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", l.typeName, l)
	case "stringUnknownMap":
		return json.Marshal(l.StringUnknownMap)
	case "voice":
		return json.Marshal(l.Voice)
	}
}

type ListVoicesListVoicesGetResponseItemVisitor interface {
	VisitStringUnknownMap(map[string]interface{}) error
	VisitVoice(*Voice) error
}

func (l *ListVoicesListVoicesGetResponseItem) Accept(visitor ListVoicesListVoicesGetResponseItemVisitor) error {
	switch l.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", l.typeName, l)
	case "stringUnknownMap":
		return visitor.VisitStringUnknownMap(l.StringUnknownMap)
	case "voice":
		return visitor.VisitVoice(l.Voice)
	}
}
