// This file was auto-generated by Fern from our API Definition.

package voicecloning

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	cambaigosdk "github.com/camb-ai/cambai-go-sdk"
	core "github.com/camb-ai/cambai-go-sdk/core"
	option "github.com/camb-ai/cambai-go-sdk/option"
	io "io"
	multipart "mime/multipart"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

func (c *Client) ListVoices(
	ctx context.Context,
	request *cambaigosdk.ListVoicesListVoicesGetRequest,
	opts ...option.RequestOption,
) ([]*cambaigosdk.ListVoicesListVoicesGetResponseItem, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://client.camb.ai/apis"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/" + "list-voices"

	queryParams, err := core.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 422:
			value := new(cambaigosdk.UnprocessableEntityError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	var response []*cambaigosdk.ListVoicesListVoicesGetResponseItem
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:          endpointURL,
			Method:       http.MethodGet,
			MaxAttempts:  options.MaxAttempts,
			Headers:      headers,
			Client:       options.HTTPClient,
			Response:     &response,
			ErrorDecoder: errorDecoder,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

func (c *Client) CreateCustomVoice(
	ctx context.Context,
	request *cambaigosdk.BodyCreateCustomVoiceCreateCustomVoicePost,
	opts ...option.RequestOption,
) (*cambaigosdk.CreateCustomVoiceOut, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://client.camb.ai/apis"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/" + "create-custom-voice"

	queryParams, err := core.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 422:
			value := new(cambaigosdk.UnprocessableEntityError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	var response *cambaigosdk.CreateCustomVoiceOut
	requestBuffer := bytes.NewBuffer(nil)
	writer := multipart.NewWriter(requestBuffer)
	if err := writer.WriteField("voice_name", fmt.Sprintf("%v", request.VoiceName)); err != nil {
		return nil, err
	}
	if err := core.WriteMultipartJSON(writer, "gender", request.Gender); err != nil {
		return nil, err
	}
	if request.Description != nil {
		if err := writer.WriteField("description", fmt.Sprintf("%v", *request.Description)); err != nil {
			return nil, err
		}
	}
	if request.PublishVoiceToMarketPlace != nil {
		if err := writer.WriteField("publish_voice_to_market_place", fmt.Sprintf("%v", *request.PublishVoiceToMarketPlace)); err != nil {
			return nil, err
		}
	}
	if request.Age != nil {
		if err := writer.WriteField("age", fmt.Sprintf("%v", *request.Age)); err != nil {
			return nil, err
		}
	}
	if request.Language != nil {
		if err := core.WriteMultipartJSON(writer, "language", *request.Language); err != nil {
			return nil, err
		}
	}
	if request.EnhanceAudio != nil {
		if err := writer.WriteField("enhance_audio", fmt.Sprintf("%v", *request.EnhanceAudio)); err != nil {
			return nil, err
		}
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	headers.Set("Content-Type", writer.FormDataContentType())

	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:          endpointURL,
			Method:       http.MethodPost,
			MaxAttempts:  options.MaxAttempts,
			Headers:      headers,
			Client:       options.HTTPClient,
			Request:      requestBuffer,
			Response:     &response,
			ErrorDecoder: errorDecoder,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
